spring.datasource.url=jdbc:mysql://localhost:3306/team_task_manager
spring.datasource.username=root
spring.datasource.password=Anithasivalasetty@2005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8082